"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AiOutlineGoogle } from "react-icons/ai";
import PricingSection from "@/components/PricingSection";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@radix-ui/react-dropdown-menu";
import { FaFemale, FaMale, FaRainbow } from "react-icons/fa";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
  } from "@/components/ui/dialog";
  import FaqDialog from "@/components/FaqDialog";
import { Video } from "./Video";
import { Slider } from "./Slider";
import { RevealFx } from "./RevealFx";
import styles from './RevealFx.module.scss';
import { LetterFx } from "./LetterFx";
import { PopupButton  } from '@typeform/embed-react';
import { Widget } from '@typeform/embed-react';
import { CameraIcon } from "@radix-ui/react-icons"

export function Bento() {
  return (
<div>
	<div className="grid grid-cols-1 lg:grid-cols-12 md:gap-6 lg:max-w-[1200px] md:mt-0 mx-auto">

        <div className="md:col-span-8 lg:col-span-9 mb-6 md:mb-0">
            <div className=" bg-stone-950 rounded-3xl rounded-tl-[60px] grid md:grid-cols-2 md:gap-0 relative">
                <span className="text-stone-100 absolute right-0 top-0 z-50 w-20 h-20 flex items-center justify-center">
                    
                    <SparkleIcon/>
                </span>
                <Link href="/login" className="absolute top-0 right-0 z-40 w-20 h-20 bg-stone-900 rounded-full hidden md:block outline outline-offset-2 outline-stone-300 hover:outline-stone-300/0">
                    <Image
                        className="z-10 hover:-rotate-6 transition-all duration-50 animate-spin duration-10000"
                        height="100"
                        width="100"
                        alt="hello"
                        src="/lens.png">
                    </Image>
                </Link>
                <Image
                    className="absolute top-0 right-0 z-10  hidden md:block"
                    height="125"
                    width="130"
                    alt="hello"
                    src="/kor.png">
                </Image>


                <div className="md:col-span-1 relative p-6 min-h-[500px]">
                    <div className="absolute left-8 bottom-[230px] max-w-96">
                        <RevealFx
                        className="pb-2"
                        speed="medium"
                        delay={0}
                        translateY={0}
                        >
                        <h1 className="text-stone-300 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem]">Stunningly lifelike photos, as if taken by a professional photographer. </h1> 
                        </RevealFx>
                    </div>
                    <div className="absolute left-8 -bottom-16 w-96">
                        <p
                        style={{
                            fontFamily: 'var(--font-family-code)'
                        }}
                        >
                        <LetterFx
                            className="text-stone-400 font-thin drop-shadow-sm [text-wrap:balance] text-md italic"
                            speed="medium"
                            trigger="instant"
                            charset={[
                            'X',
                            '@',
                            '$',
                            'a',
                            'H',
                            'z',
                            'o',
                            '0',
                            'y',
                            '#',
                            '?',
                            '*',
                            '0',
                            '1',
                            '+'
                            ]}
                        >
                            Upload your photos and let the magic happen
                        </LetterFx>
                        </p>
                        <div className="relative w-60 h-[200px] mt-6">
                            <Image
                            className="absolute left-0 top-0 rounded-full w-16 h-16 shadow-lg"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s1.png">
                            </Image>
                            <Image
                            className="absolute left-14 top-0 rounded-full w-16 h-16 shadow-lg"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s2.png">
                            </Image>
                            <Image
                            className="absolute right-16 top-0 rounded-full w-16 h-16 shadow-lg"
                            height="128"
                            width="128"
                            alt="hello"
                            src="/s4.png">
                            </Image>
                        </div>
                        
                    </div>
                </div>

                <div className="animate-in fade-in delay-300 duration-700 order-1 md:col-span-1 relative p-6 bg-cover bg-center md:bg-right rounded-3xl min-h-[700px]"  style={{ backgroundImage: "url('/ai.png')" }}>
                </div>

            </div> 

            <div className="grid gap-6 md:grid-cols-12 md:w-[79%] md:float-right mt-6 mb-6 bg-slate-100 rounded-3xl rounded-bl-[90px]  relative  shadow-md shadow-stone-600/10 transition-all duration-50 hover:shadow-xl">
                <div className="col-span-7 relative p-6 md:pt-4 md:ml-2 md:pr-0">
                    <div className="h-3 w-3 absolute right-0 top-5">
                        <span className="relative flex h-3 w-3">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-3 w-3 bg-stone-200"></span>
                        </span>
                    </div>
                    <p className=" text-stone-400 font-thin drop-shadow-sm [text-wrap:balance] text-[11px] mt-1 mr-6 text-right">Powered by <Link className="font-bold" target="_blank" href="https://blackforestlabs.ai/">FLUX AI</Link>  </p>
                    <h1 className="md:text-right mt-16 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem] text-stone-800">You rule the first impression.<span className="bg-gradient-to-r from-indigo-400 to-red-600 inline-block text-transparent bg-clip-text pb-2">Take photos with Ai.</span></h1>
                    <p className="text-stone-500 text-md mt-2 mb-6 md:text-right md:w-64 md:float-right">Fulfill yourself in this digital age and maximize its potential.</p>
                </div> 
                <div className="col-span-5">
                    <Image
                            className=" w-full md:w-72 h-auto float-right rounded-tr-[60px] rounded-br-[90px] rounded-tl-[0px] md:rounded-tr-[30px] md:rounded-br-[0px] md:rounded-bl-[60px] shadow-stone-900/40"
                            height="1152"
                            width="896"
                            alt="hello"
                            src="/baker2.jpg">
                    </Image>
                </div>                     
            </div>
        </div>

        <div className="md:col-span-4 lg:col-span-3 flex flex-col md:mb-0 md:mt-12">  

            <div className="mb-6 bg-slate-100 rounded-3xl relative p-6 shadow-md shadow-stone-600/10 transition-all duration-50 hover:shadow-xl">
                <p className="text-md mb-4">"I never thought it would, but it was good for my confidence. And my husband also seems to look at me differently "</p>
                <Image
                        className="w-10 h-10 rounded-full float-left mr-2"
                        height="512"
                        width="512"
                        alt="hello"
                        src="/square.png">
                </Image>
                <p className="text-sm font-bold align-baseline mt-6">
                    Vanda
                </p>
            </div>  

            <div className="animate-in fade-in-0  duration-300 mb-6 bg-slate-100 rounded-3xl relative p-6 shadow-md shadow-stone-600/10 transition-all duration-50 hover:shadow-xl">
                <p className="text-md mb-4">"Finally we have a uniform look on our company website! The results were quick and I couldn't be more happy with the images."</p>
                <Image
                        className="w-10 h-10 rounded-full float-left mr-2"
                        height="1006"
                        width="1006"
                        alt="hello"
                        src="/v12.png">
                </Image>
                <p className="text-sm font-bold align-baseline mt-6">
                    Barbara
                </p>
            </div> 

            <div className="animate-in fade-in duration-300 relative mb-6 min-h-96 bg-slate-100 text-stone-200 rounded-3xl p-6 shadow-md shadow-stone-600/10 transition-all duration-50 hover:shadow-xl bg-cover" style={{ backgroundImage: "url('/vx.jpg')" }}>
                <div className="absolute bottom-4">
                    <p className="text-md mb-4">"I'm a developer, and this is true science fiction"</p>
                    <Image
                        className="w-10 h-10 rounded-full float-left mr-2"
                        height="128"
                        width="128"
                        alt="hello"
                        src="/s5.png">
                    </Image>
                    <p className="text-md font-bold align-baseline mt-6">
                        - Tamas
                    </p>
                </div>
            </div>  

        </div>
        
	</div>

    <div className="lg:max-w-[1300px] mx-auto">

        <div className="grid md:grid-cols-3 gap-6">
            <div className="col-span-1 content-center transition-all w-full h-full bg-cover bg-gradient-to-r from-stone-900 from-70% via-stone-800 via-90% to-stone-900 to-99% rounded-3xl rounded-br-[60px] rounded-tr-[60px] z-10 relative p-6 shadow-md outline outline-8 hover:outline-2 hover:outline-offset-4 outline-offset-8 outline-stone-300/20 hover:outline-fuchsia-300/40 bg-left" style={{ backgroundImage: "url('/stars.png')" }}>
                 <div className="absolute left-6 top-6 opacity-40"><SparkIcon/></div>
                 <h1 className="pt-16 pb-6 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem] text-stone-200">Take your personal brand <span className="bg-gradient-to-r from-indigo-300 to-red-300 inline-block text-transparent bg-clip-text pb-2"> to the next level</span></h1>
                 {/*<p className="text-stone-200 mt-2 pb-4">With the latest technology</p>*/}
            </div>
            <div className="col-span-2 h-fit mx-auto">
                <div className="grid md:grid-cols-3 gap-6 md:gap-16 w-full relative text-center mx-auto md:pl-6 md:mt-10">
                        
                        <div className="max-w-3/4 float-right transition-all md:w-full h-full bg-stone-200 hover:bg-slate-100 rounded-3xl hover:rounded-[40px] z-10 col-span-1 relative p-6 shadow-md outline outline-8 hover:outline-2 hover:outline-offset-4 outline-offset-8 outline-stone-300/20 hover:outline-fuchsia-300/40">
                            <p className="mx-auto w-8 h-8 shadow-inner bg-stone-200 text-stone-600 rounded-full text-center content-center">1</p><br/>
                            <p className="font-bold  mb-2 leading-tight">Upload Photos</p>
                            <p className="text-sm mb-2 leading-tight">
                            Upload 8-16 photos of yourself & we train a custom AI modell for you.
                            </p>
                        </div>

                        <div className="mx-auto transition-all w-full h-full bg-stone-200 hover:bg-slate-100 rounded-3xl hover:rounded-[40px] z-10 col-span-1 relative p-6 shadow-md outline outline-8 hover:outline-2 hover:outline-offset-4 outline-offset-8 outline-stone-300/20 hover:outline-sky-300/40">
                        <p className="mx-auto w-8 h-8 shadow-inner bg-stone-200 text-stone-600 rounded-full text-center content-center">2</p><br/>
                            <p className="font-bold mb-2 leading-tight">Choose a Style</p>
                            <p className="text-sm mb-6 leading-tight">
                           Select one from our well-engineered, constantly updated style packs.
                            </p>
                        </div>

                        <div className="mx-auto transition-all w-full h-full bg-slate-100 hover:bg-slate-100 rounded-3xl hover:rounded-[40px] z-10 col-span-1 relative p-6 shadow-md outline outline-8 hover:outline-2 hover:outline-offset-4 outline-offset-8 outline-stone-300/20 hover:outline-lime-300/40">
                        <p className="mx-auto w-8 h-8 shadow-inner bg-stone-200 text-stone-600 rounded-full text-center content-center">3</p><br/>
                            <p className="font-bold mb-2 leading-tight">Harvest the result</p>
                            <p className="text-sm mb-6 leading-tight">
                            The process take about 20-30 minutes, after which you can download your photos immediately.
                            </p>
                        </div>

                        <div className="hidden md:block w-3/4 absolute top-24 left-20  h-px bg-stone-300 z-0"></div>
                </div>
            </div>
        </div>
        
    </div> 

    <div className="flex justify-center mb-12 mt-16 pt-6 pb-6  mx-auto w-full bg-stone-200 rounded-3xl rounded-tl-[0px] rounded-tr-[0px] rounded-br-[0px] rounded-bl-[0px] relative">
            <div className="scale-50 -top-24 right-0 flex items-center justify-center rounded-full p-1 text-center z-40 absolute w-72 h-72 shadow-xl bg-stone-800  outline outline-8 outline-offset-4 outline-stone-300/50">
            <h1 className="text-stone-200 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem]">Constantly updated Style Packs</h1>
        </div>
        <Slider/>
    </div>

    <div className="grid md:grid-cols-1 max-w-[1300px] mx-auto gap-6 py-6">   
            <h1 className="text-center md:pt-6 pb-4 text-stone-800 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem]">Enhance your digital presence<br/><span className="bg-gradient-to-r from-red-400  to-fuchsia-400 inline-block text-transparent bg-clip-text pb-2"> & get noticed everywhere!</span><br/></h1>
            <div className="col-span-1 grid grid-cols-1 md:grid-cols-3 md:gap-12 lg:max-w-[1200px] mx-auto">

                        <div className="outline outline-4 outline-offset-8 hover:outline-purple-400 outline-stone-300/30 mb-6 col-span-1 bg-slate-100 h-50 rounded-3xl relative shadow-md shadow-stone-600/10 hover:scale-105 transition-all duration-50 hover:shadow-xl hover:outline hover:outline-2 hover:outline-offset-1">
                            
                            {/*<div className="absolute top-3 -right-3 rounded-3xl bg-purple-400 pt-0 pb-1 pl-2 pr-2 text-center ">
                                <p className="text-lg">0.5<span className="font-normal text-sm">€/photo</span></p>
                            </div>*/}
                            <div className="p-6">  
                                <p><StarIcon/></p><br/>
                                <p className="font-bold mt-2 text-sm">1 Photo Session</p>
                                <p className="text-md md:h-20 leading-tight">1x Custom fine tuning + <br/>24 photos in the selected style</p>
                                <p className="font-normal text-5xl">
                                    14<span className="font-normal text-sm">€ /24pcs</span>
                                    <Link href="/login" className="float-right">
                                        <Button variant="outline" size="sm">Select</Button>
                                    </Link>
                                </p> 
                            </div>  
                        </div>

                        <div className="outline outline-4 outline-offset-8 hover:outline-purple-400 outline-stone-300/30 mb-6 col-span-1 bg-slate-100 h-50 rounded-3xl relative shadow-md shadow-stone-600/10 hover:scale-105 transition-all duration-50 hover:shadow-xl hover:outline hover:outline-2 hover:outline-offset-1">
                            <div className="p-6">  
                                <p><StarIcon/><StarIcon/><StarIcon/></p><br/>
                                <p className="font-bold mt-2 text-sm">3 Photo Session</p>
                                <p className="text-md  md:h-20 leading-tight">3x Custom fine tuning + <br/>3x24 photos in the selected style</p>
                                <p className="font-normal text-5xl">
                                    39<span className="font-normal text-sm">€ /72pcs</span>
                                    <Link href="/login" className="float-right">
                                        <Button variant="outline" size="sm">Select</Button>
                                    </Link>
                                </p> 
                            </div>  
                        </div>

                        <div className="outline outline-4 outline-offset-8 hover:outline-purple-400 outline-stone-300/30 mb-6 col-span-1 bg-slate-100 h-50 rounded-3xl relative shadow-md shadow-stone-600/10 hover:scale-105 transition-all duration-50 hover:shadow-xl hover:outline hover:outline-2 hover:outline-offset-1">
                            <div className="p-6">  
                                <p className="text-stone-300"><StarIconLight/><StarIconLight/><StarIconLight/><StarIconLight/><StarIconLight/></p><br/>
                                <p className="font-bold mt-2 text-sm">5 Photo Session</p>
                                <p className="text-md md:h-20 leading-tight">5x Custom fine tuning + <br/>5x24 photos in the selected style</p>
                                <p className="font-normal text-5xl">
                                    63<span className="font-normal text-sm">€ /120pcs</span>
                                    <Link href="/login" className="float-right">
                                        <Button variant="outline" size="sm" className="bg-stone-300 text-stone-800">Select</Button>
                                    </Link>
                                </p> 
                            </div>  
                        </div> 
                        
            </div>
            
    </div>  

    <div className="grid md:grid-cols-12 gap-0 max-w-[1190px] mx-auto mt-10">
        <div className="md:col-span-6">
            <Image  className="rounded-3xl h-[500px] mx-auto md:h-[650px] md:float-right w-auto" height="1152" width="737" alt="hello" src="/video.png"></Image>
            {/*<Video/>*/}
        </div>

        <div className="md:col-span-6 content-center md:mr-16">
            <div className="bg-gradient-to-r from-stone-100/0 to-stone-100 rounded-br-[90px] rounded-tr-[90px] pt-6 pb-12">
                <h1 className="text-left md:pt-12 md:max-w-[360px] text-stone-800 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem]">
                Do you need <span className="bg-gradient-to-r from-red-400  to-fuchsia-400 inline-block text-transparent bg-clip-text pb-2">something special?</span>
                </h1>
                <p className=" text-lg">An unified look for your team?<br/>
                Eye-catching advertisement with your own face?<br/>
                Custom fine tuning and image generation in any style!</p>
            </div>
        </div>
    </div>

    <div className="max-w-[960px] mx-auto bg-stone-800 rounded-[60px] relative p-6 outline outline-8 outline-offset-4 outline-stone-300/30 shadow-2xl shadow-fuchsia-700/20">
        <div className="absolute top-12 left-[52%] z-50 ml-28"><SparkleIcon/></div>
        <div className="scale-50 rotate-6 absolute -top-28 left-[52%] rounded-full bg-gradient-to-b from-white to-stone-300 outline outline-8 outline-offset-2 outline-stone-100/20 text-stone-100 z-40">
            <img className="w-64 h-64 mx-auto invert" src="/eur.png"/>
        </div>
        <div className="h-4 w-[95%] absolute top-4  bg-stone-800 z-30"></div>
        <div className="h-20 w-[95%] absolute bottom-4  bg-stone-800 z-30"></div>
        <Widget id="kqhmv5H3" style={{ width: '100%', height:'500px', borderRadius:'60px', border:'0px' }} className="bg-transparent" />
    </div>

    <div className="grid md:grid-cols-1 gap-6 mx-auto text-center w-full lg:max-w-[1200px] ">

        <div className="mt-12 min-h-96 w-full border-b border-stone-300 col-span-6 py-auto px-12 rounded-tl-3xl rounded-tr-[90px] mx-auto bg-stone-200 content-center bg-cover" >
            <p className="mt-20 md:mt-8 text-stone-800 text-center ">
            <Link href="/login" className="ml-4 hover:text-stone-700">
                Personal branding, the modern way.
                <Button variant={"google"} size={"md"} className="ml-4">Login with Google
                    <AiOutlineGoogle size={30} className="ml-2 hover:text-stone-300  text-stone-800"/>
                </Button>
            </Link> 
            </p>
        </div>
        

        <div className="col-span-6 pb-9">
            <div className="grid md:grid-cols-8 gap-6">
                <div className="col-span-2 md:border-r border-stone-300">
                    <h1 className="text-left p-6 text-stone-800 font-thin tracking-tight drop-shadow-sm [text-wrap:balance] text-4xl leading-[2.5rem] md:text-5xl md:leading-[3rem]">Rock Solid Security</h1>
                </div>
                <div className="col-span-2 text-left p-6">
                    <p className="font-bold">Training Data</p>
                    <p className="leading-tight text-xs">We delete your uploaded images immediately after the fine tune</p>
                </div>
                <div className="col-span-2 md:border-r md:border-l md:border-stone-300 text-left p-6 mb-6 md:mb-0">
                    <p className="font-bold">Modell Data</p>
                    <p className="leading-tight text-xs">We delete your data automatically 30 days after the fine tune have been created.</p>
                </div>
                <div className="col-span-2 md:border-r text-left p-6 mb-6 md:mb-0">
                    <p className="font-bold">Infrastructure</p>
                    <p className="leading-tight text-xs">Access to our database is controlled by a password-less system, all data is encrypted in transit and stored only for the period required. We will not give your data to any third party.</p>
                </div>
            </div>
        </div>

    </div>

     
  

</div>
  )
}

function CamIcon2() {
    return ( 
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" className="z-50 w-10 h-10 text-stone-800 mx-auto my-4 hover:animate-ping">
 <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
)
}

function CamIcon() {
    return ( 
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" className="absolute left-6 top-2 z-50 w-8 h-8 text-stone-200 mx-auto my-4 hover:animate-ping">
 <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
)
}

function StarIcon() {
    return (
<svg className="w-6 h-6 float-left text-stone-600/40 opacity-40" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.22303 0.665992C7.32551 0.419604 7.67454 0.419604 7.77702 0.665992L9.41343 4.60039C9.45663 4.70426 9.55432 4.77523 9.66645 4.78422L13.914 5.12475C14.18 5.14607 14.2878 5.47802 14.0852 5.65162L10.849 8.42374C10.7636 8.49692 10.7263 8.61176 10.7524 8.72118L11.7411 12.866C11.803 13.1256 11.5206 13.3308 11.2929 13.1917L7.6564 10.9705C7.5604 10.9119 7.43965 10.9119 7.34365 10.9705L3.70718 13.1917C3.47945 13.3308 3.19708 13.1256 3.25899 12.866L4.24769 8.72118C4.2738 8.61176 4.23648 8.49692 4.15105 8.42374L0.914889 5.65162C0.712228 5.47802 0.820086 5.14607 1.08608 5.12475L5.3336 4.78422C5.44573 4.77523 5.54342 4.70426 5.58662 4.60039L7.22303 0.665992Z" fill="currentColor"></path></svg> 
    )
}
function StarIconLight() {
    return (
<svg className="w-6 h-6 float-left  text-fuchsia-200" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.22303 0.665992C7.32551 0.419604 7.67454 0.419604 7.77702 0.665992L9.41343 4.60039C9.45663 4.70426 9.55432 4.77523 9.66645 4.78422L13.914 5.12475C14.18 5.14607 14.2878 5.47802 14.0852 5.65162L10.849 8.42374C10.7636 8.49692 10.7263 8.61176 10.7524 8.72118L11.7411 12.866C11.803 13.1256 11.5206 13.3308 11.2929 13.1917L7.6564 10.9705C7.5604 10.9119 7.43965 10.9119 7.34365 10.9705L3.70718 13.1917C3.47945 13.3308 3.19708 13.1256 3.25899 12.866L4.24769 8.72118C4.2738 8.61176 4.23648 8.49692 4.15105 8.42374L0.914889 5.65162C0.712228 5.47802 0.820086 5.14607 1.08608 5.12475L5.3336 4.78422C5.44573 4.77523 5.54342 4.70426 5.58662 4.60039L7.22303 0.665992Z" fill="currentColor"></path></svg> 
    )
}

function HeartIcon() {
    return (
<svg className="w-6 h-6 float-left  text-purple-300" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.35248 4.90532C1.35248 2.94498 2.936 1.35248 4.89346 1.35248C6.25769 1.35248 6.86058 1.92336 7.50002 2.93545C8.13946 1.92336 8.74235 1.35248 10.1066 1.35248C12.064 1.35248 13.6476 2.94498 13.6476 4.90532C13.6476 6.74041 12.6013 8.50508 11.4008 9.96927C10.2636 11.3562 8.92194 12.5508 8.00601 13.3664C7.94645 13.4194 7.88869 13.4709 7.83291 13.5206C7.64324 13.6899 7.3568 13.6899 7.16713 13.5206C7.11135 13.4709 7.05359 13.4194 6.99403 13.3664C6.0781 12.5508 4.73641 11.3562 3.59926 9.96927C2.39872 8.50508 1.35248 6.74041 1.35248 4.90532Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
    )
}



  export function PlusIcon() {
    return (
        <svg className="w-8 h-8" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.9 0.499976C13.9 0.279062 13.7209 0.0999756 13.5 0.0999756C13.2791 0.0999756 13.1 0.279062 13.1 0.499976V1.09998H12.5C12.2791 1.09998 12.1 1.27906 12.1 1.49998C12.1 1.72089 12.2791 1.89998 12.5 1.89998H13.1V2.49998C13.1 2.72089 13.2791 2.89998 13.5 2.89998C13.7209 2.89998 13.9 2.72089 13.9 2.49998V1.89998H14.5C14.7209 1.89998 14.9 1.72089 14.9 1.49998C14.9 1.27906 14.7209 1.09998 14.5 1.09998H13.9V0.499976ZM11.8536 3.14642C12.0488 3.34168 12.0488 3.65826 11.8536 3.85353L10.8536 4.85353C10.6583 5.04879 10.3417 5.04879 10.1465 4.85353C9.9512 4.65827 9.9512 4.34169 10.1465 4.14642L11.1464 3.14643C11.3417 2.95116 11.6583 2.95116 11.8536 3.14642ZM9.85357 5.14642C10.0488 5.34168 10.0488 5.65827 9.85357 5.85353L2.85355 12.8535C2.65829 13.0488 2.34171 13.0488 2.14645 12.8535C1.95118 12.6583 1.95118 12.3417 2.14645 12.1464L9.14646 5.14642C9.34172 4.95116 9.65831 4.95116 9.85357 5.14642ZM13.5 5.09998C13.7209 5.09998 13.9 5.27906 13.9 5.49998V6.09998H14.5C14.7209 6.09998 14.9 6.27906 14.9 6.49998C14.9 6.72089 14.7209 6.89998 14.5 6.89998H13.9V7.49998C13.9 7.72089 13.7209 7.89998 13.5 7.89998C13.2791 7.89998 13.1 7.72089 13.1 7.49998V6.89998H12.5C12.2791 6.89998 12.1 6.72089 12.1 6.49998C12.1 6.27906 12.2791 6.09998 12.5 6.09998H13.1V5.49998C13.1 5.27906 13.2791 5.09998 13.5 5.09998ZM8.90002 0.499976C8.90002 0.279062 8.72093 0.0999756 8.50002 0.0999756C8.2791 0.0999756 8.10002 0.279062 8.10002 0.499976V1.09998H7.50002C7.2791 1.09998 7.10002 1.27906 7.10002 1.49998C7.10002 1.72089 7.2791 1.89998 7.50002 1.89998H8.10002V2.49998C8.10002 2.72089 8.2791 2.89998 8.50002 2.89998C8.72093 2.89998 8.90002 2.72089 8.90002 2.49998V1.89998H9.50002C9.72093 1.89998 9.90002 1.72089 9.90002 1.49998C9.90002 1.27906 9.72093 1.09998 9.50002 1.09998H8.90002V0.499976Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
    )
}

export function SunIcon() {
    return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="p-1 w-8 h-8 float-right">
  <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 21v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21m0 0h4.5V3.545M12.75 21h7.5V10.75M2.25 21h1.5m18 0h-18M2.25 9l4.5-1.636M18.75 3l-1.5.545m0 6.205 3 1m1.5.5-1.5-.5M6.75 7.364V3h-3v18m3-13.636 10.5-3.819" />
</svg>

    )
}
export function MoonIcon() {
    return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="p-1 w-8 h-8 float-right">
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3v11.25A2.25 2.25 0 0 0 6 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0 1 18 16.5h-2.25m-7.5 0h7.5m-7.5 0-1 3m8.5-3 1 3m0 0 .5 1.5m-.5-1.5h-9.5m0 0-.5 1.5M9 11.25v1.5M12 9v3.75m3-6v6" />
</svg>
    )
}

export function UserIcon() {
    return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="p-1 w-8 h-8 float-right">
  <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
</svg>

    )
}

export function SparkIcon() {
    return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-8 h-8 text-stone-300">
  <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
</svg>
)
}


export function DiamondIcon() {
    return (
<svg className="w-10 h-10 text-stone-700 mx-auto" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.53731 0.826873C7.5125 0.824392 7.4875 0.824392 7.46269 0.826873L3.96269 1.17687C3.85672 1.18747 3.76025 1.24262 3.69736 1.32857L0.699771 5.42528C0.654046 5.48627 0.62647 5.56165 0.625057 5.6434C0.625019 5.6456 0.625 5.64781 0.625 5.65001C0.625 5.65052 0.625001 5.65103 0.625003 5.65153C0.625363 5.74237 0.658021 5.82559 0.712087 5.8903L7.21042 13.7883C7.28165 13.8749 7.38789 13.925 7.5 13.925C7.61211 13.925 7.71835 13.8749 7.78958 13.7883L14.2879 5.89031C14.342 5.8256 14.3746 5.74237 14.375 5.65153C14.375 5.65103 14.375 5.65052 14.375 5.65001C14.375 5.64849 14.375 5.64697 14.375 5.64545C14.3749 5.63963 14.3747 5.63382 14.3744 5.62801C14.37 5.55219 14.3431 5.48242 14.3002 5.42527L11.3026 1.32857C11.2397 1.24262 11.1433 1.18747 11.0373 1.17687L7.53731 0.826873ZM10.925 5.27501V5.25236L10.9223 5.27501H10.925ZM10.9342 5.17498H13.1877L11.2495 2.5261L10.9342 5.17498ZM10.5707 1.88395L8.04432 1.63131L10.1747 5.21034L10.5707 1.88395ZM6.95568 1.63131L4.42931 1.88395L4.82531 5.21034L6.95568 1.63131ZM3.75046 2.5261L1.81226 5.17498H4.0658L3.75046 2.5261ZM1.79416 6.02501L6.75861 12.0587L4.22371 6.0669C4.21787 6.0531 4.21314 6.0391 4.20949 6.02501H1.79416ZM5.15055 6.02501L7.49999 12.1085L9.84943 6.02501H9.78681H5.21319H5.15055ZM10.7905 6.02501C10.7869 6.0391 10.7821 6.0531 10.7763 6.0669L8.24139 12.0587L13.2058 6.02501H10.7905ZM7.5 2.18317L9.34038 5.27501H5.65962L7.5 2.18317Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
)
}

export function MouseIcon() {
    return (
        <svg className="w-10 h-10 text-stone-700 mx-auto" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3.29227 0.048984C3.47033 -0.032338 3.67946 -0.00228214 3.8274 0.125891L12.8587 7.95026C13.0134 8.08432 13.0708 8.29916 13.0035 8.49251C12.9362 8.68586 12.7578 8.81866 12.5533 8.82768L9.21887 8.97474L11.1504 13.2187C11.2648 13.47 11.1538 13.7664 10.9026 13.8808L8.75024 14.8613C8.499 14.9758 8.20255 14.8649 8.08802 14.6137L6.15339 10.3703L3.86279 12.7855C3.72196 12.934 3.50487 12.9817 3.31479 12.9059C3.1247 12.8301 3 12.6461 3 12.4414V0.503792C3 0.308048 3.11422 0.130306 3.29227 0.048984ZM4 1.59852V11.1877L5.93799 9.14425C6.05238 9.02363 6.21924 8.96776 6.38319 8.99516C6.54715 9.02256 6.68677 9.12965 6.75573 9.2809L8.79056 13.7441L10.0332 13.178L8.00195 8.71497C7.93313 8.56376 7.94391 8.38824 8.03072 8.24659C8.11753 8.10494 8.26903 8.01566 8.435 8.00834L11.2549 7.88397L4 1.59852Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
)
}


export function Heart2Icon() {
    return (
        <svg className="w-10 h-10 text-stone-700 mx-auto" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.89346 2.35248C3.49195 2.35248 2.35248 3.49359 2.35248 4.90532C2.35248 6.38164 3.20954 7.9168 4.37255 9.33522C5.39396 10.581 6.59464 11.6702 7.50002 12.4778C8.4054 11.6702 9.60608 10.581 10.6275 9.33522C11.7905 7.9168 12.6476 6.38164 12.6476 4.90532C12.6476 3.49359 11.5081 2.35248 10.1066 2.35248C9.27059 2.35248 8.81894 2.64323 8.5397 2.95843C8.27877 3.25295 8.14623 3.58566 8.02501 3.88993C8.00391 3.9429 7.98315 3.99501 7.96211 4.04591C7.88482 4.23294 7.7024 4.35494 7.50002 4.35494C7.29765 4.35494 7.11523 4.23295 7.03793 4.04592C7.01689 3.99501 6.99612 3.94289 6.97502 3.8899C6.8538 3.58564 6.72126 3.25294 6.46034 2.95843C6.18109 2.64323 5.72945 2.35248 4.89346 2.35248ZM1.35248 4.90532C1.35248 2.94498 2.936 1.35248 4.89346 1.35248C6.0084 1.35248 6.73504 1.76049 7.20884 2.2953C7.32062 2.42147 7.41686 2.55382 7.50002 2.68545C7.58318 2.55382 7.67941 2.42147 7.79119 2.2953C8.265 1.76049 8.99164 1.35248 10.1066 1.35248C12.064 1.35248 13.6476 2.94498 13.6476 4.90532C13.6476 6.74041 12.6013 8.50508 11.4008 9.96927C10.2636 11.3562 8.92194 12.5508 8.00601 13.3664C7.94645 13.4194 7.88869 13.4709 7.83291 13.5206C7.64324 13.6899 7.3568 13.6899 7.16713 13.5206C7.11135 13.4709 7.05359 13.4194 6.99403 13.3664C6.0781 12.5508 4.73641 11.3562 3.59926 9.96927C2.39872 8.50508 1.35248 6.74041 1.35248 4.90532Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
)
}

export function SparkleIcon() {
    return (
  <svg className="animate-ping w-4 h-4 ml-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
  </svg>
  )
  }
  
