/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/a0EqUD05Il3
 */
import Link from "next/link";
import { Badge } from "./ui/badge";
import Image from "next/image";
import { UtopiaLogo } from "./ui/utopia-logo";
import { StripeLogo } from "@/components/StripeLogo";
import { ChristmasBanner } from "./ChristmasBanner";


export function FooterV2() {
  return (
    <footer className="z-100">
 {/*}     
<div className="">
<ChristmasBanner/>
</div>
*/}
{/*
        <div className="z-[99999] fixed bottom-0 right-0 w-full bg-stone-200 text-stone-800 py-6">
          <div className="mb-4 md:mb-0">
            <UtopiaLogo/>
          </div>
          <nav>
            <ul className="text-xs flex flex-wrap justify-center md:justify-end space-x-8 md:space-x-10">
              <li>
                <Link href="/privacy" className="hover:text-gray-300 transition-colors z-100">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="mailto:tamas@utopia.express" className="hover:text-gray-300 transition-colors z-100">
                  Contact Us
                </Link>
              </li>
              <li>
                <Link href="mailto:tamas@utopia.express" className="hover:text-gray-300 transition-colors z-100">
                  Facebook
                </Link>
              </li>
            </ul>
          </nav>
        </div>
*/}
    </footer>

  )
}




function LinkIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-6 h-6 ml-1 p-1">
  <path fill-rule="evenodd" d="M4.22 11.78a.75.75 0 0 1 0-1.06L9.44 5.5H5.75a.75.75 0 0 1 0-1.5h5.5a.75.75 0 0 1 .75.75v5.5a.75.75 0 0 1-1.5 0V6.56l-5.22 5.22a.75.75 0 0 1-1.06 0Z" clip-rule="evenodd" />
</svg>

  )
}

function EmailIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-6 h-6 p-1">
  <path fill-rule="evenodd" d="M2.106 6.447A2 2 0 0 0 1 8.237V16a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8.236a2 2 0 0 0-1.106-1.789l-7-3.5a2 2 0 0 0-1.788 0l-7 3.5Zm1.48 4.007a.75.75 0 0 0-.671 1.342l5.855 2.928a2.75 2.75 0 0 0 2.46 0l5.852-2.927a.75.75 0 1 0-.67-1.341l-5.853 2.926a1.25 1.25 0 0 1-1.118 0l-5.856-2.928Z" clip-rule="evenodd" />
</svg>
  )
}








function FacebookIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function TwitterIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function LinkedinIcon() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function ArrowIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" className="">
    <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
  </svg>
 
  )
}