/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/L39ONFFHsKO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Badge } from "@/components/ui/badge";
import Image from "next/image";
import PricingSection from "./PricingSection";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AiOutlineGoogle } from "react-icons/ai";
import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "@/components/ui/table";
  import {
    HoverCard,
    HoverCardContent,
    HoverCardTrigger,
  } from "@/components/ui/hover-card";

  

export function UtopiaFaq() {
  return (

    <section className="mx-auto md:w-2/3 lg:w-1/2 py-6">

      <div className="py-6 px-4 md:px-6 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Discover your inner beauty</h2>
          <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
          This tool does not want to change you, but sees the beautiful in you, and creates an opportunity to get the most out of yourself.
          </p>
      </div>

      <div className="py-9 px-4 md:px-6 text-center">
          <div className="w-32 h-32 rounded-full mx-auto relative">
            <div className="z-40 absolute bottom-3 transition-all -right-5">
                    <HoverCard>
                            <HoverCardTrigger className="cursor-pointer pt-[11px] pl-[11px] z-40 absolute bottom-5 transition-all -right-5 text-center text-4xl font-bold tracking-tighter w-12 h-12 rounded-full border border-stone-100 bg-gradient-to-t from-stone-200 to-white shadow-lg">
                                    <SparkleIcon/>
                            </HoverCardTrigger>
                            <HoverCardContent className="w-full  mx-auto bg-transparent p-0 border-0 rounded-full">
                                <Link href="/login">
                                    <Button variant={"google"} size={"lg"}>Login with Google
                                        <AiOutlineGoogle size={20} className="ml-2"/>
                                    </Button>
                                </Link>
                            </HoverCardContent>
                    </HoverCard>
            </div>
            <Image
                        className="cover rounded-full"
                        height="933"
                        width="934"
                        alt="hello"
                        src="/v12.png"
            />
          </div>
            
          <h2 className="pt-2 text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Control The First Impression</h2>
          <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
          This tool does not want to change you, but sees the beautiful in you, and creates an opportunity to get the most out of yourself.
          </p>
          <p className="py-12">
            <Link href="/login">
              <Button variant={"google"} size={"lg"}>Login with Google
                <AiOutlineGoogle size={20} className="ml-2"/>
              </Button>
            </Link>
          </p>
      </div>

    </section>


  )
}

export function PlusIcon() {
    return (
        <svg className="w-6 h-6" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8 2.75C8 2.47386 7.77614 2.25 7.5 2.25C7.22386 2.25 7 2.47386 7 2.75V7H2.75C2.47386 7 2.25 7.22386 2.25 7.5C2.25 7.77614 2.47386 8 2.75 8H7V12.25C7 12.5261 7.22386 12.75 7.5 12.75C7.77614 12.75 8 12.5261 8 12.25V8H12.25C12.5261 8 12.75 7.77614 12.75 7.5C12.75 7.22386 12.5261 7 12.25 7H8V2.75Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
    )
}

export function SparkleIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
<path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
</svg>
)
}








