/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/L39ONFFHsKO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Badge } from "@/components/ui/badge";
import Image from "next/image";
import PricingSection from "./PricingSection";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AiOutlineGoogle } from "react-icons/ai";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function UtopiaHero() {
  return (
    <section className="w-full px-0 md:px-6 bg-stone-900">
      <div className="container shadow-2xl shadow-slate-400/10 rounded-2xl">
        <div className="grid gap-2 lg:grid-cols-[1fr_1fr] xl:grid-cols-[1.5fr_1fr]">
          <div className="content-center">
            <p><Badge variant="warning">Realism Warning!</Badge> <span className="text-xs text-slate-700 font-thin">Don't use it with other people's photos without their permission</span></p>
            <h1 className="pb-6 pt-2 bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-left font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-7xl md:leading-[4rem]">
            The AI Photographer
            </h1>
            <p className="pb-6 max-w-[420px] text-stone-700 md:text-xl">
            Upload photos of any person and create breathtakingly lifelike images with the subject!  
            </p> 
            <Link href="/login">
              <Button variant={"google"}>Login with Google
                <AiOutlineGoogle size={20} className="ml-2"/>
              </Button>
            </Link>

          </div>

          <div>
            <Image
              className="cover fade-in-5"
              height="1168"
              width="901"
              alt="hello"
              src="/v0.png"
            />

          </div>
        </div>
      </div>

    </section>
  )
}
